name: comfort_confy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  postgres: ^2.2.0
  dart_json_mapper: ^2.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.0
  provider: ^6.0.0

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  intl_utils: ^2.0.0
  build_runner: ^2.3.0

flutter:

  
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.svg

flutter_intl:
  enabled: true
  localizations:
    - path: lib/l10n
      pattern: "*.arb"