name: comfort_confy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  provider: ^6.0.0
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  device_preview: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bcrypt: ^1.1.3
  #shared_preferences: ^2.0.6
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  intl_utils: ^2.0.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter:

  disable-swift-package-manager: true
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.svg
    - assets/icons/icon.png

flutter_intl:
  enabled: true
  localizations:
    - path: lib/l10n
      pattern: "*.arb"