name: comfort_confy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  dart_json_mapper: ^2.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  #audio_session: ^0.1.6+1
  #permission_handler: ^10.0.0
  #camera: ^0.11.0+2
  #speech_to_text: ^7.0.0
  #font_awesome_flutter: ^10.1.0

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  intl_utils: ^2.0.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/icon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/icons/icon.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/icons/icon.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/icons/icon.png"
    linux:
      generate: true
      image_path: "assets/icons/icon.png"
      icons_size: 48

flutter:

  
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.svg

flutter_intl:
  enabled: true
  localizations:
    - path: lib/l10n
      pattern: "*.arb"
