name: comfort_confy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  
  flutter:
    sdk: flutter
  uuid: ^4.5.1

  supabase_flutter: ^2.8.4

  provider: ^6.0.0

  url_launcher: ^6.0.20

  clipboard: ^0.1.3

  cupertino_icons: ^1.0.6

  flutter_svg: ^2.0.9

  device_preview: ^1.2.0

  web_socket_channel: ^2.1.0

  camera: ^0.11.1

  image: ^3.0.1


  permission_handler: ^10.2.0

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  intl_utils: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0

flutter:

  disable-swift-package-manager: true
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.svg
    - assets/icons/icon.png

flutter_intl:
  enabled: true
  localizations:
    - path: lib/l10n
      pattern: "*.arb"